Repository godaddy/tartufo, pull requests merged in 2020-11, with the labels that each got.

#127 feat: Implement CODEOWNERS and auto-assignment to maintainers on PRs …
  .github/CODEOWNERS
  CHANGELOG.md
  poetry.lock
Labels: documentation

#135 Fix pypy3 testing and also support Python 3.9
  .github/workflows/ci.yml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bug, enhancement

#144 feature/update-action-versions #143: Update to latest GH Action hashes
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: enhancement

#141 Fix #140: Ensure a valid output folder name in Windows
  .github/workflows/ci.yml
  CHANGELOG.md
  docs/source/spelling_wordlist.txt
  tartufo/cli.py
  tartufo/config.py
  tests/helpers.py
  tests/test_cli.py
  tests/test_config.py
  tests/test_scan_local_repo.py
  tests/test_scan_remote_repo.py
  tests/test_util.py
Labels: CI/CD
