Repository godaddy/tartufo, pull requests merged in 2020-10, with the labels that each got.

#111 Updated docs for v2
  README.md
  docs/source/CONTRIBUTING.md
  docs/source/_static/img/example_issue.png
  docs/source/api.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/examplecleanup.rst
  docs/source/features.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/spelling_wordlist.txt
  docs/source/usage.rst
  poetry.lock
  pyproject.toml
  tartufo/cli.py
  tox.ini
Labels: documentation

#116 feat(rules): Add path specific rules (#88)
  tartufo/config.py
  tartufo/scanner.py
  tartufo/types.py
  tartufo/util.py
  tests/data/testRules.json
  tests/test_base_scanner.py
  tests/test_config.py
Labels: enhancement

#100 New pull request template
  .github/pull_request_template.md
Labels: documentation

#131 Issue 130 Add mailing list info to appropriate docs
  .github/ISSUE_TEMPLATE/question.md
  CHANGELOG.md
  docs/source/CONTRIBUTING.md
Labels: documentation

#133 Fix #117 - Ignore whitespace-only lines in exclusions files
  CHANGELOG.md
  tartufo/config.py
  tests/test_config.py
Labels: bug
