Repository godaddy/tartufo, pull requests merged in 2021-02, with the labels that each got.

#155 feature/154-Update_CoC_and_Code_Styling
  CODE_OF_CONDUCT.md
  docs/source/CONTRIBUTING.md
Labels: documentation

#157 Add success message and exclusions to output
  CHANGELOG.md
  tartufo/cli.py
  tartufo/commands/pre_commit.py
  tartufo/commands/scan_local_repo.py
  tartufo/commands/scan_remote_repo.py
  tartufo/types.py
  tartufo/util.py
  tests/test_cli.py
  tests/test_util.py
Labels: enhancement

#168 Add rust toolchain to allow for building latest cryptography
  .gitattributes
  CHANGELOG.md
  Dockerfile
  poetry.lock
Labels: CI/CD
